window.CASEFILE_SEED = {
  demoStats: {
    incidents: 40,
    evidenceRecords: 150,
    sources: 20,
    legalMatrices: 5,
    contradictionSets: 8,
    reports: 3,
    entities: 12,
  },
  sources: [
    {
      id: "SRC-HRW-2024",
      name: "Human Rights Watch / SITU / Truth Hounds",
      type: "NGO spatial investigation",
      tier: "A",
      url: "https://www.hrw.org/report/2024/02/08/our-city-was-gone/russias-devastation-mariupol-ukraine",
      status: "ready",
    },
    {
      id: "SRC-SITU-2024",
      name: "SITU Research - Beneath the Rubble",
      type: "Forensic spatial project",
      tier: "A",
      url: "https://situ.nyc/research/projects/beneath-the-rubble-documenting-devastation-and-loss-in-mariupol",
      status: "partner permission",
    },
    {
      id: "SRC-UNOSAT-3300",
      name: "UNOSAT Mariupol building damage assessment",
      type: "Satellite damage assessment",
      tier: "A",
      url: "https://unosat.org/products/3300",
      status: "inspect downloads",
    },
    {
      id: "SRC-UNOSAT-3358",
      name: "UNOSAT Azovstal industrial site assessment",
      type: "Satellite damage assessment",
      tier: "A",
      url: "https://unosat.org/products/3358",
      status: "inspect downloads",
    },
    {
      id: "SRC-OSCE-2022",
      name: "OSCE Moscow Mechanism expert report",
      type: "Legal / IHL report",
      tier: "A",
      url: "https://cdn.osce.org/sites/default/files/f/documents/f/a/515868.pdf",
      status: "ready",
    },
    {
      id: "SRC-AMNESTY-2022",
      name: "Amnesty - CHILDREN theatre strike investigation",
      type: "Incident investigation",
      tier: "A",
      url: "https://www.amnesty.org/en/documents/eur50/5713/2022/en/",
      status: "ready",
    },
    {
      id: "SRC-OHCHR-MARIUPOL",
      name: "OHCHR Mariupol update and HRMMU reports",
      type: "UN monitoring",
      tier: "A",
      url: "https://www.ohchr.org/en/statements-and-speeches/2022/06/high-commissioner-updates-human-rights-council-mariupol-ukraine",
      status: "ready",
    },
    {
      id: "SRC-ICC-UKRAINE",
      name: "ICC Situation in Ukraine",
      type: "International criminal court",
      tier: "A",
      url: "https://www.icc-cpi.int/situations/ukraine",
      status: "ready",
    },
    {
      id: "SRC-MARIUPOL-DESTRUCTION",
      name: "MariupolDestruction.com public My Maps capture",
      type: "Public map lead set",
      tier: "C",
      url: "https://www.mariupoldestruction.com/map",
      status: "privacy review required",
    },
    {
      id: "SRC-META-POLICY",
      name: "Meta Page Public Content Access / Content Library",
      type: "Platform access policy",
      tier: "C",
      url: "https://developers.facebook.com/docs/features-reference/page-public-content-access/",
      status: "credentials required",
    },
  ],
  evidence: [
    {
      id: "E-0012",
      sourceId: "SRC-AMNESTY-2022",
      source: "Witness video archive",
      title: "Explosion aftermath recorded from southeast approach",
      type: "Video",
      published: "2022-03-16 14:32",
      captured: "2024-02-11",
      language: "Ukrainian",
      reliability: "B",
      confidence: 0.78,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-DRAMA",
      legalTags: ["Civilian harm", "Protected object"],
      claims: ["C-01", "C-02", "C-03"],
      archive: "Local evidence store",
    },
    {
      id: "E-0019",
      sourceId: "SRC-HRW-2024",
      source: "NGO report",
      title: "Post-strike assessment and witness statements",
      type: "Document",
      published: "2024-02-08 09:17",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.86,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-DRAMA",
      legalTags: ["Civilian harm", "Attack on civilian object"],
      claims: ["C-01", "C-03", "C-04"],
      archive: "Source URL",
    },
    {
      id: "E-0041",
      sourceId: "SRC-UNOSAT-3300",
      source: "Satellite imagery",
      title: "Pre- and post-strike high-resolution imagery reference",
      type: "Image",
      published: "2022-03-16 10:09",
      captured: "2026-07-03",
      language: "N/A",
      reliability: "A",
      confidence: 0.88,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-DRAMA",
      legalTags: ["Damage analysis", "Protected object"],
      claims: ["C-01", "C-02", "C-03"],
      archive: "Provider archive",
    },
    {
      id: "E-0088",
      sourceId: "SRC-HRW-2024",
      source: "Witness interview",
      title: "Evacuee testimony from shelter inside theatre",
      type: "Interview",
      published: "2022-03-18 11:04",
      captured: "2024-02-26",
      language: "Russian",
      reliability: "B",
      confidence: 0.6,
      status: "In review",
      pii: "Sensitive",
      linkedIncident: "INC-DRAMA",
      legalTags: ["Civilian shelter", "Casualty estimate"],
      claims: ["C-01", "C-04"],
      archive: "Restricted excerpt",
    },
    {
      id: "E-0127",
      sourceId: "SRC-MARIUPOL-DESTRUCTION",
      source: "Public social/map post",
      title: "Photo of DETI marking on theatre forecourt",
      type: "Social post",
      published: "2022-03-16 08:47",
      captured: "2026-06-29",
      language: "Ukrainian",
      reliability: "C",
      confidence: 0.42,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-DRAMA",
      legalTags: ["Civilian marking"],
      claims: ["C-02", "C-03"],
      archive: "Public My Maps lead",
    },
    {
      id: "E-0204",
      sourceId: "SRC-OSCE-2022",
      source: "OSCE report",
      title: "Mariupol maternity hospital discussion",
      type: "Legal report",
      published: "2022-04-13 00:00",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.84,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-MATERNITY",
      legalTags: ["Medical facility", "IHL"],
      claims: ["C-11", "C-12"],
      archive: "Public PDF",
    },
    {
      id: "E-0320",
      sourceId: "SRC-OHCHR-MARIUPOL",
      source: "OHCHR statement",
      title: "Mariupol civilian casualty and access caveats",
      type: "UN statement",
      published: "2022-06-16 00:00",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.8,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-SIEGE",
      legalTags: ["Civilian casualties", "Access denial"],
      claims: ["C-21", "C-22"],
      archive: "Public web",
    },
    {
      id: "E-0417",
      sourceId: "SRC-HRW-2024",
      source: "NGO spatial report",
      title: "Residential damage pattern across Left Bank districts",
      type: "Map feature",
      published: "2024-02-08 00:00",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.73,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-RESIDENTIAL",
      legalTags: ["Indiscriminate attack", "Civilian objects"],
      claims: ["C-31", "C-32"],
      archive: "Source URL",
    },
    {
      id: "E-0522",
      sourceId: "SRC-MARIUPOL-DESTRUCTION",
      source: "Public map feature",
      title: "Cemetery and burial-site observation cluster",
      type: "Geocoded observation",
      published: "2022-05-18 00:00",
      captured: "2026-06-29",
      language: "Russian",
      reliability: "C",
      confidence: 0.46,
      status: "Privacy review",
      pii: "Possible",
      linkedIncident: "INC-CEMETERY",
      legalTags: ["Mass death indicator", "Sensitive site"],
      claims: ["C-41"],
      archive: "Public My Maps lead",
    },
    {
      id: "E-0610",
      sourceId: "SRC-UNOSAT-3358",
      source: "Satellite reference",
      title: "Azovstal industrial site damage assessment overview",
      type: "Satellite reference",
      published: "2022-06-10 00:00",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.76,
      status: "In review",
      pii: "No",
      linkedIncident: "INC-AZOVSTAL",
      legalTags: ["Industrial site", "Siege endpoint"],
      claims: ["C-51"],
      archive: "UNOSAT product page",
    },
    {
      id: "E-0711",
      sourceId: "SRC-META-POLICY",
      source: "Page-owner export sample",
      title: "Mariupol Council public page export row",
      type: "Public page post",
      published: "2022-05-17 08:35",
      captured: "2025-05-20",
      language: "Ukrainian",
      reliability: "C",
      confidence: 0.31,
      status: "Awaiting corroboration",
      pii: "No",
      linkedIncident: "INC-RESIDENTIAL",
      legalTags: ["Infrastructure destruction"],
      claims: ["C-32"],
      archive: "Demo CSV import",
    },
    {
      id: "E-0882",
      sourceId: "SRC-ICC-UKRAINE",
      source: "ICC situation page",
      title: "Ukraine situation procedural metadata",
      type: "Court source",
      published: "2022-03-02 00:00",
      captured: "2026-07-03",
      language: "English",
      reliability: "A",
      confidence: 0.9,
      status: "Reviewed",
      pii: "No",
      linkedIncident: "INC-DISPLACEMENT",
      legalTags: ["Deportation", "Transfer", "Procedural context"],
      claims: ["C-61"],
      archive: "Public web",
    },
  ],
  claims: [
    {
      id: "C-01",
      text: "The theatre was used as a civilian shelter.",
      evidenceIds: ["E-0012", "E-0019", "E-0088"],
      confidence: 0.84,
    },
    {
      id: "C-02",
      text: "The site was visibly marked for children before the strike.",
      evidenceIds: ["E-0041", "E-0127"],
      confidence: 0.81,
    },
    {
      id: "C-03",
      text: "No reliable source in the casefile establishes a military objective at the theatre.",
      evidenceIds: ["E-0019", "E-0041", "E-0127"],
      confidence: 0.69,
    },
    {
      id: "C-04",
      text: "Civilian deaths occurred, but the exact number remains range-bound.",
      evidenceIds: ["E-0019", "E-0088", "E-0320"],
      confidence: 0.72,
    },
    {
      id: "C-11",
      text: "The maternity hospital was a medical facility and visibly damaged in the 2022-03-09 attack.",
      evidenceIds: ["E-0204"],
      confidence: 0.84,
    },
    {
      id: "C-21",
      text: "The siege caused extensive civilian harm and access deprivation.",
      evidenceIds: ["E-0320", "E-0417"],
      confidence: 0.78,
    },
    {
      id: "C-31",
      text: "Residential areas show repeated damage patterns across multiple districts.",
      evidenceIds: ["E-0417", "E-0711"],
      confidence: 0.71,
    },
    {
      id: "C-41",
      text: "Burial and cemetery observations require privacy and corroboration review before publication.",
      evidenceIds: ["E-0522"],
      confidence: 0.46,
    },
    {
      id: "C-51",
      text: "Azovstal damage should be treated as a dedicated industrial-site layer.",
      evidenceIds: ["E-0610"],
      confidence: 0.76,
    },
    {
      id: "C-61",
      text: "Deportation and forcible-transfer analysis should be evidence-organized and source-bound.",
      evidenceIds: ["E-0882"],
      confidence: 0.68,
    },
  ],
  incidents: [
    {
      id: "INC-DRAMA",
      title: "Drama Theatre strike",
      type: "Airstrike / explosive weapons",
      date: "2022-03-16",
      time: "10:30 local time",
      district: "Tsentralnyi District",
      location: [47.0973, 37.5439],
      severity: "Critical",
      confidence: "High",
      confidenceValue: 0.88,
      status: "Corroborated",
      casualty: "300-600+ range-bound",
      note: "Exact figure unconfirmed; range reflects source reporting.",
      protectedSite: "Civilian shelter / cultural site",
      evidenceIds: ["E-0012", "E-0019", "E-0041", "E-0088", "E-0127"],
      legalTags: ["War crimes", "Protected civilian object", "Genocide indicator review"],
      contradictionIds: ["CON-CASUALTY", "CON-DENIAL"],
      priority: 98,
    },
    {
      id: "INC-MATERNITY",
      title: "Maternity Hospital strike",
      type: "Attack on medical facility",
      date: "2022-03-09",
      time: "Daytime",
      district: "Livoberezhnyi District",
      location: [47.1154, 37.6152],
      severity: "Critical",
      confidence: "High",
      confidenceValue: 0.84,
      status: "Corroborated",
      casualty: "17+ injured reported",
      note: "Medical-facility status and damage well supported; casualty details remain source-bound.",
      protectedSite: "Medical facility",
      evidenceIds: ["E-0204"],
      legalTags: ["War crimes", "Medical units", "Civilian harm"],
      contradictionIds: ["CON-DENIAL"],
      priority: 92,
    },
    {
      id: "INC-SIEGE",
      title: "Starvation / siege conditions",
      type: "Humanitarian access denial",
      date: "2022-03-01 - 2022-04-30",
      time: "Extended",
      district: "Citywide",
      location: [47.102, 37.62],
      severity: "High",
      confidence: "Medium",
      confidenceValue: 0.63,
      status: "Under review",
      casualty: "Citywide civilian harm",
      note: "Evidence supports severe deprivation; intent and command chain need more source work.",
      protectedSite: "Civilian population",
      evidenceIds: ["E-0320"],
      legalTags: ["Humanitarian denial", "Conditions of life", "Genocide indicator review"],
      contradictionIds: ["CON-ACCESS"],
      priority: 89,
    },
    {
      id: "INC-RESIDENTIAL",
      title: "Residential district destruction",
      type: "Area bombardment / destruction",
      date: "2022-03-16 - 2022-04-24",
      time: "Extended",
      district: "Left Bank / Primorskyi",
      location: [47.0961, 37.5418],
      severity: "High",
      confidence: "Medium",
      confidenceValue: 0.67,
      status: "In review",
      casualty: "Multiple local reports",
      note: "Map features are lead evidence until corroborated against NGO/satellite sources.",
      protectedSite: "Residential areas",
      evidenceIds: ["E-0417", "E-0711"],
      legalTags: ["Civilian objects", "Indiscriminate attack"],
      contradictionIds: ["CON-LOCATION"],
      priority: 84,
    },
    {
      id: "INC-DISPLACEMENT",
      title: "Filtration and forced displacement route",
      type: "Displacement / transfer",
      date: "2022-03-20 - 2022-05-20",
      time: "Extended",
      district: "Bezimenne corridor",
      location: [47.134, 37.75],
      severity: "High",
      confidence: "Medium",
      confidenceValue: 0.58,
      status: "Under review",
      casualty: "Population movement",
      note: "Requires stronger chain-of-custody and victim/witness privacy handling.",
      protectedSite: "Civilian population",
      evidenceIds: ["E-0882"],
      legalTags: ["Deportation", "Forcible transfer", "Crimes against humanity"],
      contradictionIds: ["CON-ATTRIBUTION"],
      priority: 78,
    },
    {
      id: "INC-CEMETERY",
      title: "Cemetery expansion observations",
      type: "Burial-site observation",
      date: "2022-04-01 - 2022-05-31",
      time: "Extended",
      district: "Mangush / city outskirts",
      location: [47.071, 37.49],
      severity: "High",
      confidence: "Low",
      confidenceValue: 0.46,
      status: "Privacy review",
      casualty: "Sensitive / unverified",
      note: "Do not expose names or exact sensitive rows in public/demo mode.",
      protectedSite: "Sensitive burial locations",
      evidenceIds: ["E-0522"],
      legalTags: ["Mass death indicator", "Evidence preservation"],
      contradictionIds: ["CON-CASUALTY"],
      priority: 73,
    },
    {
      id: "INC-AZOVSTAL",
      title: "Azovstal complex assault",
      type: "Industrial-site siege endpoint",
      date: "2022-04-11 - 2022-05-20",
      time: "Extended",
      district: "Kalmiuskyi District",
      location: [47.096, 37.653],
      severity: "Critical",
      confidence: "High",
      confidenceValue: 0.76,
      status: "In review",
      casualty: "Mixed combat/civilian context",
      note: "Keep civilian-harm and military-target analysis separate.",
      protectedSite: "Industrial site / shelters",
      evidenceIds: ["E-0610"],
      legalTags: ["Siege endpoint", "Industrial damage"],
      contradictionIds: ["CON-ATTRIBUTION"],
      priority: 86,
    },
  ],
  legalElements: [
    {
      id: "L-01",
      category: "War crimes",
      name: "Attacks on civilian objects",
      evidenceIds: ["E-0012", "E-0019", "E-0041", "E-0417"],
      bestIncidents: ["INC-DRAMA", "INC-RESIDENTIAL"],
      confidence: 82,
      contradictions: 2,
      missing: "Precise targeting data for all incidents",
      status: "Corroborated",
    },
    {
      id: "L-02",
      category: "War crimes",
      name: "Indiscriminate attack",
      evidenceIds: ["E-0019", "E-0204", "E-0417"],
      bestIncidents: ["INC-MATERNITY", "INC-RESIDENTIAL"],
      confidence: 78,
      contradictions: 2,
      missing: "Weapon-effect modeling",
      status: "Corroborated",
    },
    {
      id: "L-03",
      category: "War crimes",
      name: "Protected medical units",
      evidenceIds: ["E-0204"],
      bestIncidents: ["INC-MATERNITY"],
      confidence: 76,
      contradictions: 1,
      missing: "Additional facility logs",
      status: "Corroborated",
    },
    {
      id: "L-04",
      category: "Crimes against humanity",
      name: "Deportation or forcible transfer",
      evidenceIds: ["E-0882"],
      bestIncidents: ["INC-DISPLACEMENT"],
      confidence: 58,
      contradictions: 1,
      missing: "Orders or policy records",
      status: "Under review",
    },
    {
      id: "L-05",
      category: "Crimes against humanity",
      name: "Persecution / severe deprivation",
      evidenceIds: ["E-0320", "E-0417"],
      bestIncidents: ["INC-SIEGE", "INC-RESIDENTIAL"],
      confidence: 57,
      contradictions: 2,
      missing: "Pattern-linked perpetrator intent",
      status: "Under review",
    },
    {
      id: "L-06",
      category: "Genocide indicators",
      name: "Destructive conditions of life",
      evidenceIds: ["E-0320", "E-0417"],
      bestIncidents: ["INC-SIEGE"],
      confidence: 63,
      contradictions: 3,
      missing: "Proof of intent to destroy in whole or in part",
      status: "Under review",
    },
    {
      id: "L-07",
      category: "Genocide indicators",
      name: "Protected group harm indicators",
      evidenceIds: ["E-0320", "E-0882"],
      bestIncidents: ["INC-SIEGE", "INC-DISPLACEMENT"],
      confidence: 55,
      contradictions: 2,
      missing: "Comprehensive group membership data",
      status: "Under review",
    },
    {
      id: "L-08",
      category: "Command responsibility",
      name: "Command links to specific incidents",
      evidenceIds: ["E-0019", "E-0204", "E-0882"],
      bestIncidents: ["INC-DRAMA", "INC-MATERNITY", "INC-DISPLACEMENT"],
      confidence: 49,
      contradictions: 2,
      missing: "Direct command communications",
      status: "Gap",
    },
  ],
  contradictions: [
    {
      id: "CON-CASUALTY",
      title: "Casualty estimate range",
      type: "Casualty estimates",
      impact: "High",
      status: "Open",
      claimA: "Theatre deaths are frequently reported in the hundreds.",
      claimB: "Some investigations use lower confirmed minimums and emphasize uncertainty.",
      evidenceIds: ["E-0019", "E-0088", "E-0320"],
      resolution: "Need auditable victim lists, burial records, survivor follow-up, and source methodology comparison.",
    },
    {
      id: "CON-DENIAL",
      title: "Russian official denial narrative",
      type: "Attribution",
      impact: "High",
      status: "Open",
      claimA: "Independent and NGO sources attribute the strike to Russian forces.",
      claimB: "Russian official/state-aligned narratives deny responsibility or propose alternate causes.",
      evidenceIds: ["E-0012", "E-0019", "E-0041", "E-0127"],
      resolution: "Preserve denial as adversarial claim; compare to imagery, timing, weapon-effect analysis, and witness reports.",
    },
    {
      id: "CON-LOCATION",
      title: "Location precision variance",
      type: "Location",
      impact: "Medium",
      status: "Investigating",
      claimA: "Map lead rows often use precise pins from public My Maps.",
      claimB: "Some lead locations may represent approximate building blocks or neighborhood summaries.",
      evidenceIds: ["E-0417", "E-0711"],
      resolution: "Store source geometry and derived geometry separately with uncertainty radius.",
    },
    {
      id: "CON-ACCESS",
      title: "Humanitarian corridor status",
      type: "Time/date",
      impact: "Medium",
      status: "Open",
      claimA: "Some sources report announced corridors.",
      claimB: "Civilian accounts and monitoring sources describe blocked or unsafe movement.",
      evidenceIds: ["E-0320"],
      resolution: "Build corridor-by-date table with source, direction, outcome, and reliability tier.",
    },
    {
      id: "CON-ATTRIBUTION",
      title: "Attribution and command-chain uncertainty",
      type: "Attribution",
      impact: "High",
      status: "Open",
      claimA: "Patterns point to Russian armed forces and affiliated authorities.",
      claimB: "Incident-level command responsibility needs direct links to orders or commanders.",
      evidenceIds: ["E-0204", "E-0610", "E-0882"],
      resolution: "Separate perpetrator attribution from command responsibility until source-backed.",
    },
  ],
  timeline: [
    {
      date: "2022-02-24",
      lane: "Incidents",
      title: "Siege begins",
      evidenceIds: ["E-0320"],
      confidence: "High",
    },
    {
      date: "2022-03-09",
      lane: "Incidents",
      title: "Maternity Hospital strike",
      evidenceIds: ["E-0204"],
      confidence: "High",
    },
    {
      date: "2022-03-16",
      lane: "Incidents",
      title: "Drama Theatre strike",
      evidenceIds: ["E-0012", "E-0019", "E-0041", "E-0088", "E-0127"],
      confidence: "High",
    },
    {
      date: "2022-03-20",
      lane: "Access / evacuation",
      title: "Filtration and displacement reports intensify",
      evidenceIds: ["E-0882"],
      confidence: "Medium",
    },
    {
      date: "2022-04-01",
      lane: "Infrastructure",
      title: "Residential destruction clusters expand",
      evidenceIds: ["E-0417", "E-0711"],
      confidence: "Medium",
    },
    {
      date: "2022-04-11",
      lane: "Incidents",
      title: "Azovstal complex assault period",
      evidenceIds: ["E-0610"],
      confidence: "High",
    },
    {
      date: "2022-05-18",
      lane: "Evidence imports",
      title: "Cemetery expansion observation cluster",
      evidenceIds: ["E-0522"],
      confidence: "Low",
    },
    {
      date: "2022-05-20",
      lane: "Incidents",
      title: "Major combat phase ends after Azovstal surrender",
      evidenceIds: ["E-0610", "E-0320"],
      confidence: "High",
    },
  ],
  connectors: [
    {
      id: "manual_upload",
      name: "manual_upload",
      description: "Manual file upload",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-03 09:12",
      records: 127,
      failures: 0,
      access: "No credentials",
      connector: "manual_upload",
    },
    {
      id: "url_capture",
      name: "url_capture",
      description: "URL and webpage capture",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-02 16:08",
      records: 64,
      failures: 0,
      access: "Robots/terms checked",
      connector: "url_capture",
    },
    {
      id: "facebook_admin_export",
      name: "facebook_admin_export",
      description: "Import Facebook page-owner export CSV/JSON",
      status: "Completed",
      mode: "Manual",
      lastRun: "2025-05-20 09:14",
      records: 482,
      failures: 2,
      access: "Owner export only",
      connector: "facebook_admin_export",
    },
    {
      id: "facebook_public_page_authorized",
      name: "facebook_public_page_authorized",
      description: "Approved Graph API or research access",
      status: "Disabled",
      mode: "Credentials",
      lastRun: "Never",
      records: 0,
      failures: 0,
      access: "Requires Meta approval",
      connector: "facebook_public_page_authorized",
    },
    {
      id: "manual_social_archive",
      name: "manual_social_archive",
      description: "Lawful public social archive upload",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-01 14:33",
      records: 213,
      failures: 0,
      access: "No login automation",
      connector: "manual_social_archive",
    },
    {
      id: "destruction_map_import",
      name: "destruction_map_import",
      description: "Mariupol destruction map import",
      status: "Ready",
      mode: "Scheduled",
      lastRun: "2026-06-29 15:14",
      records: 4895,
      failures: 1,
      access: "Public lead set",
      connector: "destruction_map_import",
    },
    {
      id: "geojson_import",
      name: "geojson_import",
      description: "GeoJSON / KML import",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-06-29 15:14",
      records: 328,
      failures: 0,
      access: "File upload",
      connector: "geojson_import",
    },
    {
      id: "csv_geocoder",
      name: "csv_geocoder",
      description: "CSV batch geocoding with manual review",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-06-28 15:12",
      records: 912,
      failures: 3,
      access: "Stub geocoder",
      connector: "csv_geocoder",
    },
    {
      id: "osm_building_import",
      name: "osm_building_import",
      description: "OSM building footprint context",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-06-28 10:31",
      records: 18450,
      failures: 0,
      access: "OSM attribution required",
      connector: "osm_building_import",
    },
    {
      id: "satellite_reference_import",
      name: "satellite_reference_import",
      description: "UNOSAT / Copernicus / Maxar references",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-03 10:02",
      records: 38,
      failures: 0,
      access: "License review",
      connector: "satellite_reference_import",
    },
    {
      id: "ngo_report_import",
      name: "ngo_report_import",
      description: "NGO report extraction",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-03 09:31",
      records: 56,
      failures: 0,
      access: "Public report",
      connector: "ngo_report_import",
    },
    {
      id: "news_article_import",
      name: "news_article_import",
      description: "News article metadata and citations",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-02 12:09",
      records: 74,
      failures: 0,
      access: "Copyright limited",
      connector: "news_article_import",
    },
    {
      id: "legal_document_import",
      name: "legal_document_import",
      description: "ICC / OSCE / OHCHR legal documents",
      status: "Ready",
      mode: "Manual",
      lastRun: "2026-07-03 09:31",
      records: 74,
      failures: 0,
      access: "Public documents",
      connector: "legal_document_import",
    },
  ],
  imports: [
    {
      id: "IMP-2026-06-29-1514",
      connector: "destruction_map_import",
      status: "Completed with issues",
      records: 4895,
      failures: 1,
      duration: "00:03:41",
      startedBy: "analyst",
      created: "4,895 map features, 10,593 media refs",
    },
    {
      id: "IMP-2026-07-03-0931",
      connector: "legal_document_import",
      status: "Completed",
      records: 74,
      failures: 0,
      duration: "00:00:56",
      startedBy: "analyst",
      created: "Legal source records and review tasks",
    },
    {
      id: "IMP-2025-05-20-0912",
      connector: "facebook_admin_export",
      status: "Completed",
      records: 482,
      failures: 2,
      duration: "00:02:18",
      startedBy: "analyst",
      created: "Evidence leads, locations, claim candidates",
    },
  ],
  researchGaps: [
    {
      topic: "HRW/SITU structured layers",
      type: "Partner permission",
      priority: "High",
      next: "Request GeoJSON/CSV/vector exports and reuse terms.",
    },
    {
      topic: "Casualty figures",
      type: "Quantification",
      priority: "High",
      next: "Compare OHCHR, NGO, city, AP, and burial-record methodologies.",
    },
    {
      topic: "UNOSAT downloads/license",
      type: "Geospatial QA",
      priority: "High",
      next: "Inspect product 3300/3358 download formats and license status.",
    },
    {
      topic: "Facebook exact page URLs",
      type: "Access compliance",
      priority: "High",
      next: "Confirm via official sites; ingest only owner export or approved API.",
    },
    {
      topic: "Command chain",
      type: "Attribution",
      priority: "Medium",
      next: "Separate incident attribution from command-responsibility analysis.",
    },
    {
      topic: "Sensitive burial rows",
      type: "Privacy",
      priority: "High",
      next: "Suppress PII and precise sensitive sites in public/demo mode.",
    },
  ],
  reports: [
    {
      id: "RPT-SIEGE",
      title: "Siege overview brief",
      template: "Mariupol siege overview",
      status: "Draft",
      sections: ["Executive summary", "Key findings", "Timeline of events", "Spatial analysis", "Sources and methodology"],
      citationIds: ["E-0019", "E-0320", "E-0417", "E-0882"],
    },
    {
      id: "RPT-DRAMA",
      title: "Drama Theatre incident memo",
      template: "Incident memo",
      status: "In review",
      sections: ["Incident summary", "Evidence stack", "Contradictions", "Legal element mapping"],
      citationIds: ["E-0012", "E-0019", "E-0041", "E-0088", "E-0127"],
    },
    {
      id: "RPT-GENOCIDE-INDICATORS",
      title: "Genocide-indicator research memo",
      template: "Indicator coverage review",
      status: "Not legal conclusion",
      sections: ["Indicator coverage", "Missing evidence", "Alternative explanations", "Research plan"],
      citationIds: ["E-0320", "E-0417", "E-0882"],
    },
  ],
};
